name: Clojure CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: "1.10.1"
      - name: Lint format
        run: clojure -A:fmt check
      - name: Run tests
        run: clojure -A:test
